### ISSUE TITLE
common_stage: arterial measurement labels

### ISSUE THREAD

**Issue by michela-meister** [ratschlab/HIRID-ICU-Benchmark#19]
Hello,
We are trying to work with data on oxygen saturation in arterial blood (concept ID 20000800 the [hirid variable reference](https://docs.google.com/spreadsheets/d/1MjihfhyXX4dwni8Fxy3Ji5RCvSvnhipDCyjYo_6rixY/edit#gid=1345496616) spreadsheet). In the appendix of the [original HiRID paper](https://www.nature.com/articles/s41591-020-0789-4.pdf), the authors explain that the raw data includes venous measurements that were incorrectly labeled as arterial, and they had to correct these measurements during preprocessing (which they do [here](https://github.com/ratschlab/circEWS/blob/master/preprocessing/step1a_2_remove_oor_values.py) with with the function change_arterial_to_venous). Do the common_stage matrices include the correct labels for arterial measurements?

**Comment by hugoych** [comment]
Hi Michela,
Thanks for using our benchmark!

The `common stage` matrices are not corrected for possible arterial/venous artifacts beyond out-of-range removal from the [`varref.tsv`](https://github.com/ratschlab/HIRID-ICU-Benchmark/blob/master/preprocessing/resources/varref.tsv) table as other variables. This is because the pipeline up to the `common stage` aims to not depend on any design/modeling choices as discussed in the paper. Indeed the [`change_arterial_to_venous`](https://github.com/ratschlab/circEWS/blob/b2b1f00dac4f5d46856a2c7abe2ca4f12d4c612d/preprocessing/step1a_2_remove_oor_values.py#L84) function, from the original repo, relies on a given threshold parameter to define mislabeled arterial S02 measurements. Because this only affects less than 400 measurements out of more than 3M, we preferred not to include this step. For the same reason, we only removed out-of-range height and weight and did not include the [`correct_weight_height`](https://github.com/ratschlab/circEWS/blob/b2b1f00dac4f5d46856a2c7abe2ca4f12d4c612d/preprocessing/step1a_2_remove_oor_values.py#L172) function from the original repo. 
I hope this answers your question!
