### ISSUE TITLE
Elaboration of pharma type information

### ISSUE THREAD

**Issue by KaiWU17TUM** [ratschlab/HIRID-ICU-Benchmark#27]
Hi, I am working on a project to learn patients' responses to medication.
Pure computer science student with very little knowledge in the medical field.

For the pharma data, is there an easy way to determine if it is a continuous infusion or a one-time injection/drug?

In the raw pharma data, 
- "type" column - only tells if it is fluid or drug. Does injection belong to fluid or drug?
- "infusionid" - I am curious how this one is assigned. Is there a unique ID for each use of medicine among all patients?
- "subtype" - does this help to tell the difference?
- "route" - could you elaborate on what these abbreviations mean?

`['iv-inj', 'iv-inf', 'ep-inj', 'inhal', 'p os', 'p.ms', 'p.o',
'cv-inj', 'cv-inf', 'ms', 'p rectal', 'sc-inj', 'transcutan',
'paravert.', 'subling', 'p rect', 'parav.Bolus', 'enteral',
'ep-inf', None, 'nasal', 'iv', 'intercostal', 'i.ventr, EVD',
'Inh.Beatmung', 'ip-inf', 'im-inj', 'nasal_', 'per-iv']`

Thanks for all the work on this dataset and making it publicly accessible :)

**Comment by XinruiLyu** [comment]
Hi, 
We inferred whether the drug is continuous infusion or one-time injection/tablet from the `status` column. If the status value is 780 or 544, then the drug is one-time injection/tablet/etc. If the status value is 524, that indicates the start of an infusion; and if the status value is 776, that indicates the stop of the infusion. And the invalid status values are `[522, 526, 546, 782]`, records with one of these status values can be discarded because they were invalid. You can find these information in [these lines](https://github.com/ratschlab/HIRID-ICU-Benchmark/blob/bee770094bf8389920bc09823895b87e09a563dd/icu_benchmarks/common/constants.py) in `icu_benchmarks/common/constants.py`. Let me know if you have follow-up questions.

**Comment by KaiWU17TUM** [comment]
Thanks! I should have checked this repo thoroughly. The preprocessing scripts help a lot :)
